service: aws-lambda-receiver-bolt-js
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-east-2
functions:
  slack:
    handler: app.handler
    events:
      - http:
          path: slack/events
          method: post
plugins:
  - serverless-offline