name: Node.js CI

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14']
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create env file
      run: |
        touch .env
        echo SLACK_SIGNING_SECRET=${{ secrets.SLACK_SIGNING_SECRET }} >> .env
        echo SLACK_TOKEN=${{ secrets.SLACK_TOKEN }} >> .env
    - name: Install NPM dependencies
      run: npm ci
    - name: Run project
      run: npm start
  # - name: Run tests
  #   run: npm test
  # - name: SonarCloud Scan
      # uses: SonarSource/sonarcloud-github-action@master
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      #   SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}